### ISSUE TITLE
Expected results from codebase

### ISSUE THREAD

**Issue by cinjon** [batra-mlp-lab/lang-emerge#2]
What is the expected result from running run_me.sh with and without GPU wrt timing and success?

Thanks!

**Comment by satwikkottur** [comment]
(a) Exact timing would depend on the type of hardware you are running the code on. But in general, CPU time >> GPU time.

(b) Both the executions should ideally give rise to similar results.

**Comment by cinjon** [comment]
And what results do you expect?

**Comment by satwikkottur** [comment]
I am not sure if I understand your question completely. This repository contains code for "Natural Language Does Not Emerge 'Naturally' in Multi-Agent Dialog" paper (https://arxiv.org/abs/1706.08502), which was submitted to EMNLP 2017.

**Comment by cinjon** [comment]
I'm familiar with the paper. If you run this with the default settings, there's a train/test accuracy report. I'm asking what curves for those accuracies do you expect?

**Comment by satwikkottur** [comment]
The default settings are `V_Q=3, V_A=4` and memoryless Q-Bot (Sec 4.3). The training accuracy should increase to 100% (code terminates when this happens) while the agents are learning their policies. Test accuracy should be around 75% in expectation.
