### ISSUE TITLE
Clarify the license?

### ISSUE THREAD

**Issue by eugene-kharitonov** [batra-mlp-lab/lang-emerge#5]
Hello @satwikkottur ,

Thanks for sharing the code.

Could you please clarify which license the code is published under? The Readme.md says it is BSD, so I assume it is https://opensource.org/licenses/BSD-2-Clause not https://opensource.org/licenses/BSD-3-Clause ?

Thanks!

**Comment by satwikkottur** [comment]
Hello @eugene-kharitonov,

Thanks for your interest. The code is published under BSD-3.
