### ISSUE TITLE
torch.cat() confusion

### ISSUE THREAD

**Issue by jinan-zhou** [batra-mlp-lab/lang-emerge#6]
In chatbots.py, line 127

`features = torch.cat(embeds.transpose(0, 1), 1)`

It causes the error
`TypeError: cat() received an invalid combination of arguments - got (Tensor, int), but expected one of: 
(tuple of Tensors tensors, name dim, Tensor out)
(tuple of Tensors tensors, int dim, Tensor out)`

Also, I do not understand what this statement means. What is concatenating one vector? According to my observateion, the `embeds.transpose(0, 1)` is a tensor of size [3,1000,20]. What transformation does the statement intend to do?

**Comment by satwikkottur** [comment]
Hello @DeeperMind , 

What version of PyTorch are you using? I believe this code is compatible only with PyTorch 0.4.

**Comment by jinan-zhou** [comment]
Hello @satwikkottur ,

Thank you for your reply. However, I tried to run with PyTorch 0.4.0 and encountered the similar error at this line:

`TypeError: cat(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor`

Really appreciate if you could give an environment, or docker container that runs the code.

**Comment by satwikkottur** [comment]
Hello @DeeperMind ,

I've updated the repository to make it compatible with Python 3.6 and PyTorch 1.4. Let me know if you need anything else.

**Comment by jinan-zhou** [comment]
Thank you for your great work! @satwikkottur 
Just two minor questions, what does Tr and Te mean in the training output? And are there any ways to retrieve the conversations?

**Comment by satwikkottur** [comment]
I've fixed visualization (`test.py`) script after the update. Check `run_me.sh` to see how to use call the script. Hope this helps!

P.S.: Tr and Te are the task accuracies of the agents using greedy policy on the complete train and test set, respectively.
